config/routes.rb
Simsearch::Application.routes.draw do

  match 'feedbacks' => 'feedbacks#create', :as => :feedback

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  root :to => 'frontdoor#root'
  
  get "home" => "frontdoor#home"
  
  get "signin" => "frontdoor#identity"
  get "signout" => "frontdoor#identity"
  get "register" => "frontdoor#identity"
  get "subscribe" => "frontdoor#identity"
  get "profile" => "frontdoor#profile"
  get "searches" => "searches#searches"

  get "privacy" => "frontdoor#privacy"
  get "terms" => "frontdoor#terms"
  get "capitaliq" => "frontdoor#capitaliq"
  get "about" => "frontdoor#about"
  get "factor_definitions" => "frontdoor#factor_definitions"

  post "signin" => "frontdoor#signin"
  post "register" => "frontdoor#register"
  post "signout" => "frontdoor#destroy_session"
  post "update_username" => "frontdoor#update_username"
  post "update_password" => "frontdoor#update_password"

  get "autocomplete_security_ticker" => "frontdoor#autocomplete_security_ticker" # to autocomplete

  post "search" => "frontdoor#search"  # to evaluate the submitted search content
  get "search" => "frontdoor#search_with_id" # to retrieve earlier search results.
  get "search_detail" => "frontdoor#search_detail"

  post "share" => "searches#share"
  post "addfavorite" => "searches#addfavorite"

  # API calls that return JSON only, no rendering of HTML templates.
  get "get_search_results" => "frontdoor#get_search_results"
  get "get_search_summary" => "frontdoor#get_search_summary"
  get "get_search_info" => "frontdoor#get_search_info"
  get "get_price_time_series" => "frontdoor#get_price_time_series"
  get "get_growth_time_series" => "frontdoor#get_growth_time_series"
  get "get_security_snapshot" => "frontdoor#get_security_snapshot"
  get "get_share_history" => "searches#get_share_history"
end

app/models/feedback.rb
class Feedback
  attr_accessor :subject, :email, :comment, :page

  def initialize(params = {})
    self.subject = params[:subject]
    self.email = params[:email]
    self.comment = params[:comment]
    self.page = params[:page]
  end

  def valid?
    self.comment && !self.comment.strip.blank?
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  layout false

  def new
    @feedback = Feedback.new(page: request.referer)
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    if @feedback.valid?
      FeedbackMailer.feedback(@feedback).deliver
      render :status => :created, :text => '<h3>Thank you for your feedback!</h3>'
    else
      @error_message = "Please enter your #{@feedback.subject.to_s.downcase}"

      # Returns the whole form back. This is not the most effective
      # use of AJAX as we could return the error message in JSON, but
      # it makes easier the customization of the form with error messages
      # without worrying about the javascript.
      render :action => 'new', :status => :unprocessable_entity
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper

  def feedback_tab(options = {})
    feedback_init({'position' => 'top'}.merge(options.stringify_keys))
  end

  def feedback_init(options = {})
    options = {
      "position" => "null"
    }.merge(options.stringify_keys)

    options['position'] = "'#{options['position']}'" unless options['position'].blank? || options['position'] == 'null'
    content_tag 'script', :type => "text/javascript" do
      "$(document).ready(function() { $('.feedback_link').feedback({tabPosition: #{options["position"]}}); });".html_safe
    end
  end

  def feedback_link(text, options = {})
    link_to text, '#', :class => "feedback_link"
  end
end

app/views/feedbacks/new.html.erb
<div class="modal-header">
<h3>Feedback</h3>
</div>
  <% if current_user %>
  <p>Hi <b><%= current_user.username %></b>, thank you for giving us feedback. </p>
  <% else %>
  <p>Thank you for taking the time to leave us feedback.</p>
  <% end %>

  <%= form_for @feedback, :as => :feedback, :url => feedback_path, :html => {:id => "feedback_form"} do |f| %>
    <%= f.hidden_field 'page' %>
    <% unless @error_message.blank? %>
      <p class="error">
        <%=h @error_message %>
      </p>
    <% end %>

    <p>
      <% if current_user %>
        <%= f.text_field 'email', :maxlength => 128, :value => current_user.email, :style => "display:none" %>      
      <% else %>
        <%= f.label 'Please enter your e-mail address below:' %>
        <%= f.text_field 'email', :maxlength => 128 %>
      <% end %>
    </p>
    <p>
      <%= f.label 'Please enter your comments below. (max 1024 characters)' %>
      <%= f.text_area 'comment', :rows => 5, :cols => 30, :maxlength => 1024, :style => "resize:none" %>
    </p>
    <%= f.submit 'Send', :class => "btn btn-primary btn-large", :style => "margin-right:10%;margin-left:auto;display:block" %>
  <% end %>